---
- name: cluster consul servers
  hosts: consul_servers
  remote_user: root
  vars:
    leader_ip: "{{ groups['consul_servers_private'][0] }}"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: ensure consul is running
    systemd:
      name: consul-server.service
      state: started
  - name: join the leader node
    shell:
      cmd: consul join {{leader_ip}}

