---
- name: cluster consul servers
  hosts: consul
  remote_user: root
  vars:
    leader_ip: "10.116.0.4"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: ensure consul is running
    systemd:
      name: consul-server.service
      state: started
  - name: join the leader node
    shell:
      cmd: consul join {{leader_ip}}

